export const dummyStamps = [
    {
      id: 1,
      title: 'Legendary Poets of Odisha',
      image: '/images/image0.jpg',
      minting: 'Now',
      price: 500,
      rarity: 55,
      description: 'A collection celebrating the legendary poets of Odisha.',
      creator: 'Ashley',
      owner: 'Aleena',
      releaseDate: '2023-01-15',
      shortTitle: 'Legendary Poets',
      numOfReviews: 3945,
      likes: 1250, // Number of likes
    },
    {
      id: 2,
      title: 'Gopabandhu Das',
      image: '/images/image1.jpg',
      minting: 'Now',
      price: 300,
      rarity: 45,
      description: 'Commemorating the esteemed Gopabandhu Das.',
      creator: 'Vandita',
      owner: 'Samiksha',
      releaseDate: '2022-11-05',
      shortTitle: 'Gopabandhu Das',
      numOfReviews: 1573,
      likes: 845, // Number of likes
    },
    {
      id: 3,
      title: 'North-East Orchids Collection Postcards-Set of 10',
      image: '/images/postcards3.jpg',
      minting: 'In 1 week',
      price: 349,
      rarity: 65,
      description: 'A collection of 6 postcards showcasing traditional dance forms of India.',
      creator: 'Ira',
      owner: 'Sneha',
      releaseDate: '2023-08-01',
      shortTitle: 'Traditional Dance Forms',
      numOfReviews: 980,
      likes: 1032, // Number of likes
    },
    {
      id: 4,
      title: '100th Birth Anniversary of Karpoor Thakur',
      image: '/images/image3.jpg',
      minting: 'Now',
      price: 600,
      rarity: 70,
      description: 'Celebrating the 100th birth anniversary of Karpoor Thakur.',
      creator: 'Daisman',
      owner: 'Vineet',
      releaseDate: '2023-04-01',
      shortTitle: 'Karpoor Thakur Anniversary',
      numOfReviews: 892,
      likes: 980, // Number of likes
    },
    {
      id: 5,
      title: 'Halloluck 64 Pcs Vintage Retro Classic Movie Postcards, Collectable Vintage Postcards',
      image: '/images/postcards5.jpg',
      minting: 'Now',
      price: 349,
      rarity: 50,
      description: 'A set of 10 postcards featuring monuments from North-East India.',
      creator: 'Gunjan',
      owner: 'Ashwani',
      releaseDate: '2022-12-20',
      shortTitle: 'North-East Monument',
      numOfReviews: 643,
      likes: 721, // Number of likes
    },
    {
      id: 6,
      title: '64 Pcs 2 Set Vintage Retro Old Travel Postcards, Collectable Vintage Postcards',
      image: '/images/postcards6.jpg',
      minting: 'Now',
      price: 349,
      rarity: 55,
      description: 'A collection of 8 watercolor postcards featuring botanical illustrations.',
      creator: 'Abhidha',
      owner: 'Prasukh',
      releaseDate: '2022-09-15',
      shortTitle: 'Botanicals Water Colour',
      numOfReviews: 1254,
      likes: 843, // Number of likes
    },
    {
      id: 7,
      title: 'North-East Birds Collection Postcards - Set of 10',
      image: '/images/postcards4.jpg',
      minting: 'Now',
      price: 359,
      rarity: 65,
      description: 'Set of 6 postcards showcasing objects from Assam.',
      creator: 'Yana',
      owner: 'Ghania',
      releaseDate: '2023-02-28',
      shortTitle: 'Objects of Assam',
      numOfReviews: 1789,
      likes: 956, // Number of likes
    },
    {
      id: 8,
      title: 'Srila Bhaktisiddhanta Saraswati Prabhupada',
      image: '/images/image2.jpg',
      minting: 'Now',
      price: 250,
      rarity: 60,
      description: 'Honoring Srila Bhaktisiddhanta Saraswati Prabhupada.',
      creator: 'Shuvro',
      owner: 'Sachin',
      releaseDate: '2022-08-10',
      shortTitle: 'Srila Bhaktisiddhanta',
      numOfReviews: 2100,
      likes: 1123, // Number of likes
    },
    {
      id: 9,
      title: 'Mountain Peaks of the Himalayas - Scenic Postcard',
      image: '/images/postcards7.jpg',
      minting: 'Now',
      price: 299,
      rarity: 60,
      description: 'Set of 5 postcards featuring the highest peaks of India.',
      creator: 'Mira',
      owner: 'Shaan',
      releaseDate: '2023-07-12',
      shortTitle: 'Mountain Peaks',
      numOfReviews: 1305,
      likes: 911, // Number of likes
    },
    {
      id: 10,
      title: 'India Postcard Pack (Pack of 14)',
      image: '/images/postcards2.jpg',
      minting: 'Now',
      price: 399,
      rarity: 50,
      description: 'Set of 8 postcards featuring historical landmarks across India.',
      creator: 'Anaya',
      owner: 'Rahul',
      releaseDate: '2022-10-10',
      shortTitle: 'Historical Landmarks',
      numOfReviews: 1370,
      likes: 1089, // Number of likes
    },
    {
      id: 11,
      title: 'Divine Greetings From India Post card (Beauty of India) - Set of 9 Postcard (2 Set)',
      image: '/images/postcards1.jpg',
      minting: 'In 1 week',
      price: 349,
      rarity: 65,
      description: 'A collection of 6 postcards showcasing traditional dance forms of India.',
      creator: 'Ira',
      owner: 'Sneha',
      releaseDate: '2023-08-01',
      shortTitle: 'Traditional Dance Forms',
      numOfReviews: 980,
      likes: 1001, // Number of likes
    },
    {
      id: 12,
      title: 'North-East Orchids Collection Postcards - Set of 10',
      image: '/images/image7.jpg',
      minting: 'In 2 days',
      price: 469,
      rarity: 75,
      description: 'A set of 10 postcards featuring orchids from the North-East.',
      creator: 'Aryan',
      owner: 'Sarthak',
      releaseDate: '2023-06-15',
      shortTitle: 'North-East Orchids',
      numOfReviews: 432,
      likes: 671, // Number of likes
    },
  ];
  