export const dummyStamps = [
  {
      id: 1,
      title: 'Legendary Poets of Odisha',
      image: '/images/image0.jpg',
     
      minting: 'Now',
      price: 500,
      rarity: 55,
      description: 'A collection celebrating the legendary poets of Odisha.',
      creator: 'Ashley',
      owner: 'Aleena',
      releaseDate: '2023-01-15',
      shortTitle: 'Legendary Poets',
      numOfReviews: 3945, // Number of reviews
  },
  {
      id: 2,
      title: 'Gopabandhu Das',
      image: '/images/image1.jpg',
      minting: 'Now',
      price: 300,
      rarity: 45,
      description: 'Commemorating the esteemed Gopabandhu Das.',
      creator: 'Vandita',
      owner: 'Samiksha',
      releaseDate: '2022-11-05',
      shortTitle: 'Gopabandhu Das',
      numOfReviews: 1573, // Number of reviews
  },
  {
      id: 3,
      title: 'Srila Bhaktisiddhanta Saraswati Prabhupada',
      image: '/images/image2.jpg',
      minting: 'Now',
      price: 250,
      rarity: 60,
      description: 'Honoring Srila Bhaktisiddhanta Saraswati Prabhupada.',
      creator: 'Shuvro',
      owner: 'Sachin',
      releaseDate: '2022-08-10',
      shortTitle: 'Srila Bhaktisiddhanta',
      numOfReviews: 2100, // Number of reviews
  },
  {
      id: 4,
      title: '100th Birth Anniversary of Karpoor Thakur',
      image: '/images/image3.jpg',
      minting: 'Now',
      price: 600,
      rarity: 70,
      description: 'Celebrating the 100th birth anniversary of Karpoor Thakur.',
      creator: 'Daisman',
      owner: 'Vineet',
      releaseDate: '2023-04-01',
      shortTitle: 'Karpoor Thakur Anniversary',
      numOfReviews: 892, // Number of reviews
  },
  {
      id: 5,
      title: 'North-East Monument Collection Postcards - Set of 10',
      image: '/images/image4.jpg',
      minting: 'Now',
      price: 349,
      rarity: 50,
      description: 'A set of 10 postcards featuring monuments from North-East India.',
      creator: 'Gunjan',
      owner: 'Ashwani',
      releaseDate: '2022-12-20',
      shortTitle: 'North-East Monument',
      numOfReviews: 643, // Number of reviews
  },
  {
      id: 6,
      title: 'Botanicals - Water Colour Collection Postcards - Set of 8',
      image: '/images/image5.jpg',
      minting: 'Now',
      price: 349,
      rarity: 55,
      description: 'A collection of 8 watercolor postcards featuring botanical illustrations.',
      creator: 'Abhidha',
      owner: 'Prasukh',
      releaseDate: '2022-09-15',
      shortTitle: 'Botanicals Water Colour',
      numOfReviews: 1254, // Number of reviews
  },
  {
      id: 7,
      title: 'Objects of Assam Collection Postcards - Set of 6',
      image: '/images/image6.jpg',
      minting: 'Now',
      price: 359,
      rarity: 65,
      description: 'Set of 6 postcards showcasing objects from Assam.',
      creator: 'Yana',
      owner: 'Ghania',
      releaseDate: '2023-02-28',
      shortTitle: 'Objects of Assam',
      numOfReviews: 1789, // Number of reviews
  },
  {
      id: 8,
      title: 'North-East Orchids Collection Postcards - Set of 10',
      image: '/images/image7.jpg',
      minting: 'In 2 days',
      price: 469,
      rarity: 75,
      description: 'A set of 10 postcards featuring orchids from the North-East.',
      creator: 'Aryan',
      owner: 'Sarthak',
      releaseDate: '2023-06-15',
      shortTitle: 'North-East Orchids',
      numOfReviews: 432, // Number of reviews
  },
];
